name: make-release

on:
  workflow_dispatch

jobs:
  release:
    runs-on: windows-latest
    env: 
      GH_TOKEN: ${{ github.token }}
      
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: prepare
        id: prepare
        shell: pwsh
        run: |
          $json = Get-Content .\info.json | ConvertFrom-Json
          $version = $json.version
          $full_name = "memory-cards_$version"
          $archive = "$full_name.zip"
          echo "archive=$archive" >> "$env:GITHUB_ENV"
          echo "version=$version" >> "$env:GITHUB_ENV"
          echo "out_dir=$full_name" >> "$env:GITHUB_ENV"
                  
      - name: Collect files
        shell: pwsh
        run: robocopy . "$env:out_dir" /XD ".vscode" ".git" ".github" /XF ".gitignore" "readme.md" "*.xcf" "publish.ps1" /S

      - name: Compress archive
        shell: pwsh
        run: |
          $PSNativeCommandUseErrorActionPreference = $false
          Compress-Archive -Path $env:out_dir -CompressionLevel Optimal -DestinationPath $env:archive

      - name: Release
        run: gh release create "v$env:version" "$env:archive" --notes "v$env:version" --title "v$env:version" --draft
