name: make-release

on:
  workflow_dispatch

jobs:
  release:
    runs-on: windows-latest
    env: 
      GH_TOKEN: ${{ github.token }}
      
    steps:
      - uses: actions/checkout@v4
      - name: checkout master
        run: git checkout master
